@tool
extends EditorPlugin

const MANIFEST_PATH := "res://Cargo.toml"
const CRATE_ROOT_PATH := "res://src/lib.rs"
const INDEX_PATH := "res://src/scripts/mod.rs"
const CARGO_CONFIG_PATH := "res://.cargo/config.toml"

var _godot_rust_plugin


func _enter_tree() -> void:
	call_deferred("_run_setup_flow")


func _run_setup_flow() -> void:
	for _frame in 5:
		await get_tree().process_frame
	_godot_rust_plugin = get_tree().get_first_node_in_group(
		&"godot_rust_editor_plugin"
	)
	if _godot_rust_plugin == null:
		_fail("The godot-rust editor plugin is absent from the editor tree")
		return
	var workflow_deadline := Time.get_ticks_msec() + 30_000
	while Time.get_ticks_msec() < workflow_deadline:
		if _godot_rust_plugin.call(&"is_workflow_configured"):
			break
		await get_tree().process_frame
	if not _godot_rust_plugin.call(&"is_workflow_configured"):
		_fail("godot-rust did not inspect the existing Cargo package")
		return
	if _godot_rust_plugin.call(&"is_auto_check_enabled"):
		_fail("The incomplete Cargo package was reported as ready")
		return
	if FileAccess.file_exists(INDEX_PATH) or FileAccess.file_exists(CARGO_CONFIG_PATH):
		_fail("godot-rust modified the package before setup was confirmed")
		return

	for child in _godot_rust_plugin.get_children():
		if child is ConfirmationDialog:
			child.hide()
	_godot_rust_plugin.call(&"_configure_project")
	var setup_deadline := Time.get_ticks_msec() + 30_000
	while Time.get_ticks_msec() < setup_deadline:
		if (
			FileAccess.file_exists(INDEX_PATH)
			and FileAccess.file_exists(CARGO_CONFIG_PATH)
			and _godot_rust_plugin.call(&"is_auto_check_enabled")
		):
			break
		await get_tree().process_frame
	if not _godot_rust_plugin.call(&"is_auto_check_enabled"):
		_fail("godot-rust did not finish Script Mode setup")
		return

	var manifest := _read_text(MANIFEST_PATH)
	if (
		"# preserve this Cargo comment" not in manifest
		or "godot_rs = { path =" not in manifest
		or 'crate-type = ["cdylib", "rlib"]' not in manifest
		or "[package.metadata.godot-rust]" not in manifest
	):
		_fail("Script Mode setup did not preserve and complete Cargo.toml")
		return
	var crate_root := _read_text(CRATE_ROOT_PATH)
	if (
		"pub fn existing_user_code() -> u32 { 7 }" not in crate_root
		or "mod scripts;" not in crate_root
	):
		_fail("Script Mode setup did not preserve and complete src/lib.rs")
		return
	var index := _read_text(INDEX_PATH)
	if (
		"@generated by godot-rust" not in index
		or "godot_rs::script_module!" not in index
	):
		_fail("Script Mode setup did not create the generated script index")
		return
	var cargo_config := _read_text(CARGO_CONFIG_PATH)
	if 'target-dir = ".godot/rust/target"' not in cargo_config:
		_fail("Script Mode setup did not isolate Cargo build products")
		return
	print("GODOT_RUST_SETUP_USER_FILES_PRESERVED")
	print("GODOT_RUST_SETUP_CONFIGURED")

	if not bool(_godot_rust_plugin.call(&"_build")):
		_fail("The configured empty Script Mode project did not build")
		return
	if not FileAccess.file_exists("res://.godot/rust/last-known-good.json"):
		_fail("The configured project did not publish Last Known Good")
		return
	print("GODOT_RUST_SETUP_BUILD_SUCCEEDED")
	get_tree().quit()


func _read_text(path: String) -> String:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return ""
	return file.get_as_text()


func _fail(message: String) -> void:
	push_error("godot-rust editor setup test: %s" % message)
	get_tree().quit(1)
