// @generated by godot-rust; script files themselves are user-owned.
#[path = "base_greeting.rs"]
mod godot_rs_script_a30789f6b1436d33;
#[path = "game_tuning.rs"]
mod godot_rs_script_56e37ef512eff9fe;
#[path = "hello.rs"]
mod godot_rs_script_d695de4c27ef9ed8;

godot_rs::script_module! {
    godot_rs_script_a30789f6b1436d33::BaseGreeting => ("res://src/scripts/base_greeting.rs", "uid://e2"),
    godot_rs_script_56e37ef512eff9fe::GameTuning => ("res://src/scripts/game_tuning.rs", "uid://d2"),
    godot_rs_script_d695de4c27ef9ed8::Hello => ("res://src/scripts/hello.rs", "uid://b2"),
}
