use crate::managed_fs::{atomic_write, ensure_directory, has_managed_header};
use crate::{GodotRustMode, ProjectKind, inspect_cargo_project, probe_project};
use godot_rs_api_policy::GodotApiVersion;
use serde::Serialize;
use std::io;
use std::path::{Component, Path, PathBuf};
use toml_edit::{Array, DocumentMut, InlineTable, Item, Table, TableLike, Value, value};

const DEFAULT_SCRIPTS_PATH: &str = "src/scripts";
const DEFAULT_TARGET_DIRECTORY: &str = ".godot/rust/target";
const GENERATED_INDEX_HEADER_LINE: &str =
    "// @generated by godot-rust; script files themselves are user-owned.";
const MAX_MANAGED_FILE_BYTES: u64 = 4 * 1024 * 1024;
const VSCODE_SETTINGS: &str = r#"{
    "rust-analyzer.linkedProjects": ["./Cargo.toml"],
    "rust-analyzer.check.command": "clippy",
    "rust-analyzer.cargo.targetDir": ".godot/rust/rust-analyzer-target"
}
"#;
const VSCODE_TASKS: &str = r#"{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "godot-rust: check",
            "type": "process",
            "command": "cargo",
            "args": ["check", "--all-targets"],
            "problemMatcher": ["$rustc"],
            "group": "build"
        },
        {
            "label": "godot-rust: build",
            "type": "process",
            "command": "cargo",
            "args": ["build"],
            "problemMatcher": ["$rustc"],
            "group": {"kind": "build", "isDefault": true}
        },
        {
            "label": "godot-rust: test",
            "type": "process",
            "command": "cargo",
            "args": ["test"],
            "problemMatcher": ["$rustc"],
            "group": "test"
        }
    ]
}
"#;
const VSCODE_LAUNCH: &str = r#"{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "godot-rust: Attach with CodeLLDB",
            "type": "lldb",
            "request": "attach",
            "pid": "${command:pickMyProcess}",
            "sourceLanguages": ["rust"]
        },
        {
            "name": "godot-rust: Attach with GDB",
            "type": "cppdbg",
            "request": "attach",
            "program": "${input:godotExecutable}",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb"
        }
    ],
    "inputs": [
        {
            "id": "godotExecutable",
            "type": "promptString",
            "description": "Absolute path to the Godot executable"
        }
    ]
}
"#;

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct ProjectSetupOutcome {
    pub root: PathBuf,
    pub manifest_path: PathBuf,
    pub package_name: String,
    pub crate_root: PathBuf,
    pub scripts_path: PathBuf,
    pub index_path: PathBuf,
    pub cargo_config_path: PathBuf,
    pub godot_rs_requirement: String,
    pub changed_files: Vec<PathBuf>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct WorkspaceSelectionOutcome {
    pub workspace_root: PathBuf,
    pub manifest_path: PathBuf,
    pub package: String,
    pub changed: bool,
}

struct ManifestPlan {
    contents: String,
    package_name: String,
    crate_root: PathBuf,
    scripts_path: PathBuf,
    godot_api: GodotApiVersion,
}

struct FileEdit {
    path: PathBuf,
    purpose: &'static str,
    original: Option<Vec<u8>>,
    replacement: Vec<u8>,
}

pub fn godot_rs_version_requirement() -> String {
    let mut components = env!("CARGO_PKG_VERSION").split('.');
    let major = components.next().unwrap_or("0");
    let minor = components.next().unwrap_or("1");
    format!("{major}.{minor}")
}

pub fn select_workspace_package(
    root: impl AsRef<Path>,
    package_name: &str,
    cargo: Option<impl AsRef<std::ffi::OsStr>>,
) -> Result<WorkspaceSelectionOutcome, String> {
    let root = root.as_ref().canonicalize().map_err(|error| {
        format!(
            "could not resolve Godot project root `{}`: {error}",
            root.as_ref().display()
        )
    })?;
    let model = inspect_cargo_project(&root, cargo)?;
    if model.workspace_root != root {
        return Err(format!(
            "Cargo workspace root `{}` does not match the Godot project root `{}`",
            model.workspace_root.display(),
            root.display()
        ));
    }
    let matches = model
        .packages
        .iter()
        .filter(|package| package.name == package_name)
        .collect::<Vec<_>>();
    let [package] = matches.as_slice() else {
        return Err(format!(
            "Workspace package name `{package_name}` is missing or ambiguous"
        ));
    };
    if !package.godot_rust_enabled
        || package.godot_rust_mode == Some(GodotRustMode::Extension)
        || !package.configuration_issues.is_empty()
        || package.cdylib_targets.len() != 1
    {
        return Err(format!(
            "Workspace package `{package_name}` is not a valid Script Mode project module"
        ));
    }

    let manifest_path = root.join("Cargo.toml");
    let original = read_regular_file(
        &manifest_path,
        MAX_MANAGED_FILE_BYTES,
        "Workspace Cargo.toml",
    )?;
    let source = std::str::from_utf8(&original)
        .map_err(|_| "Workspace Cargo.toml is not valid UTF-8 and was not modified".to_owned())?;
    let replacement = plan_workspace_selection(source, package_name)?;
    let changed = replacement.as_bytes() != original;
    if changed {
        atomic_write(
            &manifest_path,
            replacement.as_bytes(),
            "Workspace Cargo.toml",
        )?;
    }
    Ok(WorkspaceSelectionOutcome {
        workspace_root: root,
        manifest_path,
        package: package_name.to_owned(),
        changed,
    })
}

fn plan_workspace_selection(source: &str, package_name: &str) -> Result<String, String> {
    if package_name.is_empty() || package_name.chars().any(char::is_control) {
        return Err("Workspace package name is empty or contains control characters".to_owned());
    }
    let mut document = source.parse::<DocumentMut>().map_err(|error| {
        format!("Workspace Cargo.toml is invalid and was not modified: {error}")
    })?;
    let workspace = document
        .get_mut("workspace")
        .and_then(Item::as_table_like_mut)
        .ok_or_else(|| {
            "Godot project Cargo.toml has no [workspace] table and was not modified".to_owned()
        })?;
    let metadata = ensure_table(workspace, "metadata", "Cargo.toml [workspace.metadata]")?;
    let configuration = ensure_table(
        metadata,
        "godot-rust",
        "Cargo.toml [workspace.metadata.godot-rust]",
    )?;
    configuration.insert("package", value(package_name));
    Ok(document.to_string())
}

pub fn configure_project(root: impl AsRef<Path>) -> Result<ProjectSetupOutcome, String> {
    let probe = probe_project(root)?;
    let package_name = match &probe.kind {
        ProjectKind::Package { name, .. } => name,
        kind => {
            return Err(format!(
                "godot-rust can configure only a Cargo package in the Godot project root; \
                 current project state is {kind:?}"
            ));
        }
    };
    let manifest_original =
        read_regular_file(&probe.manifest_path, MAX_MANAGED_FILE_BYTES, "Cargo.toml")?;
    let manifest_text = std::str::from_utf8(&manifest_original)
        .map_err(|_| "Cargo.toml is not valid UTF-8 and was not modified".to_owned())?;
    let requirement = godot_rs_version_requirement();
    let manifest_plan = plan_manifest(&probe.root, manifest_text, package_name, &requirement)?;

    let crate_root = probe.root.join(&manifest_plan.crate_root);
    let scripts_path = probe.root.join(&manifest_plan.scripts_path);
    let index_path = scripts_path.join("mod.rs");
    let cargo_config_path = select_cargo_config_path(&probe.root);

    let mut edits = Vec::new();
    push_edit_if_changed(
        &mut edits,
        probe.manifest_path.clone(),
        "Cargo.toml",
        Some(manifest_original),
        manifest_plan.contents.into_bytes(),
    );

    let crate_root_original =
        read_optional_regular_file(&crate_root, MAX_MANAGED_FILE_BYTES, "Rust crate root")?;
    let crate_root_contents =
        plan_crate_root(crate_root_original.as_deref(), &crate_root)?.into_bytes();
    push_edit_if_changed(
        &mut edits,
        crate_root.clone(),
        "Rust crate root",
        crate_root_original,
        crate_root_contents,
    );

    let index_original =
        read_optional_regular_file(&index_path, MAX_MANAGED_FILE_BYTES, "Rust script index")?;
    let index_contents = plan_script_index(index_original.as_deref(), &index_path)?;
    push_edit_if_changed(
        &mut edits,
        index_path.clone(),
        "Rust script index",
        index_original,
        index_contents,
    );

    let config_original = read_optional_regular_file(
        &cargo_config_path,
        MAX_MANAGED_FILE_BYTES,
        "Cargo configuration",
    )?;
    let config_contents = plan_cargo_config(
        config_original.as_deref(),
        &cargo_config_path,
        manifest_plan.godot_api,
    )?
    .into_bytes();
    push_edit_if_changed(
        &mut edits,
        cargo_config_path.clone(),
        "Cargo configuration",
        config_original,
        config_contents,
    );
    for (relative, purpose, contents) in [
        (
            ".vscode/settings.json",
            "VS Code rust-analyzer settings",
            VSCODE_SETTINGS,
        ),
        (".vscode/tasks.json", "VS Code Cargo tasks", VSCODE_TASKS),
        (
            ".vscode/launch.json",
            "VS Code native debugger settings",
            VSCODE_LAUNCH,
        ),
    ] {
        let path = probe.root.join(relative);
        if read_optional_regular_file(&path, MAX_MANAGED_FILE_BYTES, purpose)?.is_none() {
            push_edit_if_changed(
                &mut edits,
                path,
                purpose,
                None,
                contents.as_bytes().to_vec(),
            );
        }
    }

    validate_edit_parents(&probe.root, &edits)?;
    let changed_files = apply_edits(&probe.root, &edits)?;
    Ok(ProjectSetupOutcome {
        root: probe.root,
        manifest_path: probe.manifest_path,
        package_name: manifest_plan.package_name,
        crate_root,
        scripts_path,
        index_path,
        cargo_config_path,
        godot_rs_requirement: requirement,
        changed_files,
    })
}

pub(crate) fn sync_cargo_api_config(
    root: impl AsRef<Path>,
    godot_api: GodotApiVersion,
) -> Result<Option<PathBuf>, String> {
    let root = root.as_ref();
    let cargo_config_path = select_cargo_config_path(root);
    let original = read_optional_regular_file(
        &cargo_config_path,
        MAX_MANAGED_FILE_BYTES,
        "Cargo configuration",
    )?;
    let replacement =
        plan_cargo_config(original.as_deref(), &cargo_config_path, godot_api)?.into_bytes();
    if original.as_deref() == Some(replacement.as_slice()) {
        return Ok(None);
    }
    let edits = [FileEdit {
        path: cargo_config_path.clone(),
        purpose: "Cargo configuration",
        original,
        replacement,
    }];
    validate_edit_parents(root, &edits)?;
    apply_edits(root, &edits)?;
    Ok(Some(cargo_config_path))
}

fn plan_manifest(
    root: &Path,
    source: &str,
    probed_package_name: &str,
    requirement: &str,
) -> Result<ManifestPlan, String> {
    let mut document = source
        .parse::<DocumentMut>()
        .map_err(|error| format!("Cargo.toml is invalid and was not modified: {error}"))?;
    let package = document
        .get_mut("package")
        .and_then(Item::as_table_like_mut)
        .ok_or_else(|| "Cargo.toml [package] must be a table and was not modified".to_owned())?;
    let package_name = package
        .get("name")
        .and_then(Item::as_str)
        .ok_or_else(|| "Cargo.toml [package].name must be a string".to_owned())?
        .to_owned();
    if package_name != probed_package_name {
        return Err("Cargo.toml changed while godot-rust was preparing setup".to_owned());
    }

    let workspace_dependency = document
        .get("workspace")
        .and_then(Item::as_table_like)
        .and_then(|workspace| workspace.get("dependencies"))
        .and_then(Item::as_table_like)
        .and_then(|dependencies| dependencies.get("godot_rs"));
    if let Some(dependency) = workspace_dependency {
        validate_sdk_dependency(dependency, "Cargo.toml [workspace.dependencies].godot_rs")?;
    }
    let workspace_dependency = workspace_dependency.is_some();

    let crate_root = {
        let lib = ensure_table(document.as_table_mut(), "lib", "Cargo.toml [lib]")?;
        if lib
            .get("proc-macro")
            .and_then(Item::as_bool)
            .unwrap_or(false)
        {
            return Err(
                "Cargo.toml configures a proc-macro library; it cannot also be the godot-rust project module"
                    .to_owned(),
            );
        }
        ensure_crate_types(lib)?;
        let value = lib
            .get("path")
            .map(|item| {
                item.as_str()
                    .ok_or_else(|| "Cargo.toml [lib].path must be a string".to_owned())
            })
            .transpose()?
            .unwrap_or("src/lib.rs");
        validate_relative_file_path(value, "[lib].path")?
    };

    {
        let dependencies = ensure_table(
            document.as_table_mut(),
            "dependencies",
            "Cargo.toml [dependencies]",
        )?;
        if let Some(dependency) = dependencies.get("godot_rs") {
            validate_sdk_dependency(dependency, "Cargo.toml [dependencies].godot_rs")?;
        } else if workspace_dependency {
            let mut inherited = InlineTable::new();
            inherited.insert("workspace", Value::from(true));
            dependencies.insert("godot_rs", Item::Value(Value::InlineTable(inherited)));
        } else {
            dependencies.insert("godot_rs", value(requirement));
        }
    }

    let (scripts_path, godot_api) = {
        let package = document
            .get_mut("package")
            .and_then(Item::as_table_like_mut)
            .expect("validated package table");
        let metadata = ensure_table(package, "metadata", "Cargo.toml [package.metadata]")?;
        let configuration = ensure_table(
            metadata,
            "godot-rust",
            "Cargo.toml [package.metadata.godot-rust]",
        )?;
        validate_script_configuration(configuration)?;
        insert_default(configuration, "enabled", value(true));
        insert_default(configuration, "mode", value("script"));
        insert_default(configuration, "godot", value("4.4"));
        insert_default(configuration, "scripts", value(DEFAULT_SCRIPTS_PATH));
        insert_default(configuration, "auto-check", value(true));
        insert_default(configuration, "build-before-play", value(true));
        insert_default(configuration, "auto-build-on-idle", value(false));
        let scripts = configuration
            .get("scripts")
            .and_then(Item::as_str)
            .expect("script configuration validation guarantees a string");
        let godot_api = configuration
            .get("godot")
            .and_then(Item::as_str)
            .expect("script configuration validation guarantees a Godot API")
            .parse::<GodotApiVersion>()
            .expect("script configuration validation guarantees a supported Godot API");
        (
            validate_relative_directory_path(scripts, "package.metadata.godot-rust.scripts")?,
            godot_api,
        )
    };

    for path in [&crate_root, &scripts_path] {
        if root.join(path).starts_with(root) {
            continue;
        }
        return Err(format!(
            "godot-rust managed path must remain inside the project: {}",
            path.display()
        ));
    }

    Ok(ManifestPlan {
        contents: document.to_string(),
        package_name,
        crate_root,
        scripts_path,
        godot_api,
    })
}

fn validate_sdk_dependency(dependency: &Item, description: &str) -> Result<(), String> {
    if let Some(version) = dependency.as_str() {
        if version.is_empty() {
            return Err(format!("{description} must not use an empty version"));
        }
        return Ok(());
    }
    let Some(specification) = dependency.as_table_like() else {
        return Err(format!(
            "{description} must be a Cargo dependency string or table"
        ));
    };
    if specification
        .get("optional")
        .is_some_and(|item| item.as_bool() != Some(false))
    {
        return Err(format!(
            "{description} is optional; godot-rust will not overwrite that choice"
        ));
    }
    if specification
        .get("package")
        .is_some_and(|item| item.as_str() != Some("godot_rs"))
    {
        return Err(format!(
            "{description} refers to another Cargo package; godot-rust will not overwrite it"
        ));
    }
    Ok(())
}

fn ensure_crate_types(lib: &mut dyn TableLike) -> Result<(), String> {
    let Some(item) = lib.get_mut("crate-type") else {
        let mut types = Array::new();
        types.push("cdylib");
        types.push("rlib");
        lib.insert("crate-type", value(types));
        return Ok(());
    };
    let types = item
        .as_array_mut()
        .ok_or_else(|| "Cargo.toml [lib].crate-type must be an array of strings".to_owned())?;
    if types.iter().any(|item| item.as_str().is_none()) {
        return Err("Cargo.toml [lib].crate-type must contain only strings".to_owned());
    }
    for required in ["cdylib", "rlib"] {
        if !types.iter().any(|item| item.as_str() == Some(required)) {
            types.push(required);
        }
    }
    Ok(())
}

fn validate_script_configuration(configuration: &dyn TableLike) -> Result<(), String> {
    if configuration
        .get("enabled")
        .is_some_and(|item| item.as_bool() != Some(true))
    {
        return Err(
            "existing package.metadata.godot-rust.enabled is not `true`; setup did not overwrite it"
                .to_owned(),
        );
    }
    if let Some(mode) = configuration.get("mode") {
        match mode.as_str() {
            Some("script") => {}
            Some("extension") => {
                return Err(
                    "existing package.metadata.godot-rust.mode selects Extension Mode; \
                     Script Mode setup did not modify Cargo.toml"
                        .to_owned(),
                );
            }
            _ => {
                return Err(
                    "existing package.metadata.godot-rust.mode is not `script`; setup did not \
                     overwrite it"
                        .to_owned(),
                );
            }
        }
    }
    if let Some(item) = configuration.get("godot") {
        let target = item.as_str().ok_or_else(|| {
            "existing package.metadata.godot-rust.godot must be a string".to_owned()
        })?;
        target.parse::<GodotApiVersion>().map_err(|error| {
            format!("existing package.metadata.godot-rust.godot is invalid: {error}")
        })?;
    }
    if let Some(item) = configuration.get("scripts") {
        if item.as_str().is_none() {
            return Err("existing package.metadata.godot-rust.scripts must be a string".to_owned());
        }
    }
    for key in ["auto-check", "build-before-play", "auto-build-on-idle"] {
        if configuration
            .get(key)
            .is_some_and(|item| item.as_bool().is_none())
        {
            return Err(format!(
                "existing package.metadata.godot-rust.{key} must be a boolean"
            ));
        }
    }
    Ok(())
}

fn insert_default(table: &mut dyn TableLike, key: &str, item: Item) {
    if !table.contains_key(key) {
        table.insert(key, item);
    }
}

fn ensure_table<'a>(
    parent: &'a mut dyn TableLike,
    key: &str,
    description: &str,
) -> Result<&'a mut dyn TableLike, String> {
    if !parent.contains_key(key) {
        parent.insert(key, Item::Table(Table::new()));
    }
    parent
        .get_mut(key)
        .and_then(Item::as_table_like_mut)
        .ok_or_else(|| format!("{description} must be a table"))
}

fn plan_crate_root(original: Option<&[u8]>, path: &Path) -> Result<String, String> {
    let Some(original) = original else {
        return Ok("mod scripts;\n".to_owned());
    };
    let source = std::str::from_utf8(original)
        .map_err(|_| format!("Rust crate root is not UTF-8: {}", path.display()))?;
    let syntax = syn::parse_file(source).map_err(|error| {
        format!(
            "Rust crate root must parse before godot-rust can add `mod scripts;`: {}: {error}",
            path.display()
        )
    })?;
    if let Some(module) = syntax.items.iter().find_map(|item| match item {
        syn::Item::Mod(module) if module.ident == "scripts" => Some(module),
        _ => None,
    }) {
        if module.content.is_some() {
            return Err(format!(
                "Rust crate root already defines an inline `scripts` module; setup did not modify {}",
                path.display()
            ));
        }
        return Ok(source.to_owned());
    }
    let mut updated = source.to_owned();
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    if !updated.is_empty() && !updated.ends_with("\n\n") {
        updated.push('\n');
    }
    updated.push_str("mod scripts;\n");
    Ok(updated)
}

fn plan_script_index(original: Option<&[u8]>, path: &Path) -> Result<Vec<u8>, String> {
    let Some(original) = original else {
        return Ok(
            format!("{GENERATED_INDEX_HEADER_LINE}\ngodot_rs::script_module! {{\n}}\n")
                .into_bytes(),
        );
    };
    if !has_managed_header(original, GENERATED_INDEX_HEADER_LINE.as_bytes()) {
        return Err(format!(
            "refusing to replace user-owned Rust module index `{}`; move it or add the godot-rust generated header",
            path.display()
        ));
    }
    std::str::from_utf8(original)
        .map_err(|_| format!("Rust script index is not UTF-8: {}", path.display()))?;
    Ok(original.to_vec())
}

fn select_cargo_config_path(root: &Path) -> PathBuf {
    let modern = root.join(".cargo/config.toml");
    let legacy = root.join(".cargo/config");
    if modern.exists() || !legacy.exists() {
        modern
    } else {
        legacy
    }
}

fn plan_cargo_config(
    original: Option<&[u8]>,
    path: &Path,
    godot_api: GodotApiVersion,
) -> Result<String, String> {
    let source = match original {
        Some(bytes) => std::str::from_utf8(bytes)
            .map_err(|_| format!("Cargo configuration is not UTF-8: {}", path.display()))?,
        None => "",
    };
    let mut document = source.parse::<DocumentMut>().map_err(|error| {
        format!(
            "Cargo configuration is invalid and was not modified: {}: {error}",
            path.display()
        )
    })?;
    let build = ensure_table(
        document.as_table_mut(),
        "build",
        "Cargo configuration [build]",
    )?;
    insert_default(build, "target-dir", value(DEFAULT_TARGET_DIRECTORY));
    let environment = ensure_table(document.as_table_mut(), "env", "Cargo configuration [env]")?;
    let mut selected_api = InlineTable::new();
    selected_api.insert("value", Value::from(godot_api.to_string()));
    selected_api.insert("force", Value::from(true));
    environment.insert(
        godot_rs_api_policy::GODOT_API_ENV,
        Item::Value(Value::InlineTable(selected_api)),
    );
    Ok(document.to_string())
}

fn validate_relative_file_path(value: &str, key: &str) -> Result<PathBuf, String> {
    let path = validate_relative_path(value, key)?;
    if path.file_name().is_none() {
        return Err(format!("{key} must identify a file"));
    }
    Ok(path)
}

fn validate_relative_directory_path(value: &str, key: &str) -> Result<PathBuf, String> {
    validate_relative_path(value, key)
}

fn validate_relative_path(value: &str, key: &str) -> Result<PathBuf, String> {
    let path = Path::new(value);
    if value.is_empty()
        || path.is_absolute()
        || path.components().any(|component| {
            matches!(
                component,
                Component::ParentDir | Component::RootDir | Component::Prefix(_)
            )
        })
        || path
            .components()
            .all(|component| component == Component::CurDir)
    {
        return Err(format!(
            "{key} must be a non-empty relative path without `..`"
        ));
    }
    Ok(path.to_path_buf())
}

fn read_regular_file(path: &Path, limit: u64, purpose: &str) -> Result<Vec<u8>, String> {
    read_optional_regular_file(path, limit, purpose)?
        .ok_or_else(|| format!("{purpose} does not exist: {}", path.display()))
}

fn read_optional_regular_file(
    path: &Path,
    limit: u64,
    purpose: &str,
) -> Result<Option<Vec<u8>>, String> {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(format!(
                "could not inspect {purpose} `{}`: {error}",
                path.display()
            ));
        }
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(format!(
            "{purpose} must be a regular file: {}",
            path.display()
        ));
    }
    if metadata.len() > limit {
        return Err(format!(
            "{purpose} exceeds the {limit} byte safety limit: {}",
            path.display()
        ));
    }
    std::fs::read(path)
        .map(Some)
        .map_err(|error| format!("could not read {purpose} `{}`: {error}", path.display()))
}

fn push_edit_if_changed(
    edits: &mut Vec<FileEdit>,
    path: PathBuf,
    purpose: &'static str,
    original: Option<Vec<u8>>,
    replacement: Vec<u8>,
) {
    if original.as_deref() == Some(replacement.as_slice()) {
        return;
    }
    edits.push(FileEdit {
        path,
        purpose,
        original,
        replacement,
    });
}

fn validate_edit_parents(root: &Path, edits: &[FileEdit]) -> Result<(), String> {
    for edit in edits {
        let parent = edit
            .path
            .parent()
            .ok_or_else(|| format!("managed file has no parent: {}", edit.path.display()))?;
        let relative = parent.strip_prefix(root).map_err(|_| {
            format!(
                "managed file must remain inside the Godot project: {}",
                edit.path.display()
            )
        })?;
        let mut current = root.to_path_buf();
        for component in relative.components() {
            current.push(component.as_os_str());
            match std::fs::symlink_metadata(&current) {
                Ok(metadata) if metadata.file_type().is_symlink() => {
                    return Err(format!(
                        "managed directory must not be a symbolic link: {}",
                        current.display()
                    ));
                }
                Ok(metadata) if !metadata.is_dir() => {
                    return Err(format!(
                        "managed path component is not a directory: {}",
                        current.display()
                    ));
                }
                Ok(_) => {}
                Err(error) if error.kind() == io::ErrorKind::NotFound => break,
                Err(error) => {
                    return Err(format!(
                        "could not inspect managed directory `{}`: {error}",
                        current.display()
                    ));
                }
            }
        }
    }
    Ok(())
}

fn apply_edits(root: &Path, edits: &[FileEdit]) -> Result<Vec<PathBuf>, String> {
    let mut created_directories = Vec::new();
    for (applied, edit) in edits.iter().enumerate() {
        if let Err(error) = ensure_parent_directories(root, &edit.path, &mut created_directories)
            .and_then(|()| atomic_write(&edit.path, &edit.replacement, edit.purpose))
        {
            let rollback = rollback_edits(edits, applied, &created_directories);
            return Err(match rollback {
                Ok(()) => error,
                Err(rollback_error) => {
                    format!("{error}; setup rollback also failed: {rollback_error}")
                }
            });
        }
    }
    Ok(edits.iter().map(|edit| edit.path.clone()).collect())
}

fn ensure_parent_directories(
    root: &Path,
    path: &Path,
    created: &mut Vec<PathBuf>,
) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| format!("managed file has no parent: {}", path.display()))?;
    let relative = parent.strip_prefix(root).map_err(|_| {
        format!(
            "managed file must remain inside the Godot project: {}",
            path.display()
        )
    })?;
    let mut current = root.to_path_buf();
    for component in relative.components() {
        current.push(component.as_os_str());
        if !current.exists() {
            ensure_directory(&current, "godot-rust managed directory")?;
            created.push(current.clone());
        } else {
            ensure_directory(&current, "godot-rust managed directory")?;
        }
    }
    Ok(())
}

fn rollback_edits(
    edits: &[FileEdit],
    applied: usize,
    created_directories: &[PathBuf],
) -> Result<(), String> {
    let mut errors = Vec::new();
    for edit in edits[..applied].iter().rev() {
        let result = match &edit.original {
            Some(original) => atomic_write(&edit.path, original, edit.purpose),
            None => std::fs::remove_file(&edit.path).map_err(|error| {
                format!(
                    "could not remove newly created {} `{}`: {error}",
                    edit.purpose,
                    edit.path.display()
                )
            }),
        };
        if let Err(error) = result {
            errors.push(error);
        }
    }
    for directory in created_directories.iter().rev() {
        if let Err(error) = std::fs::remove_dir(directory) {
            if error.kind() != io::ErrorKind::NotFound {
                errors.push(format!(
                    "could not remove newly created directory `{}`: {error}",
                    directory.display()
                ));
            }
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("; "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_TEMP: AtomicU64 = AtomicU64::new(0);

    struct TempProject(PathBuf);

    impl TempProject {
        fn with_manifest(manifest: &str, crate_root: Option<&str>) -> Self {
            let id = NEXT_TEMP.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "godot-rust-project-setup-{}-{id}",
                std::process::id()
            ));
            std::fs::create_dir_all(path.join("src")).expect("temporary project directory");
            std::fs::write(path.join("project.godot"), b"[application]\n").expect("project file");
            std::fs::write(path.join("Cargo.toml"), manifest).expect("manifest");
            if let Some(crate_root) = crate_root {
                std::fs::write(path.join("src/lib.rs"), crate_root).expect("crate root");
            }
            Self(path)
        }
    }

    impl Drop for TempProject {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn workspace_selection_preserves_manifest_and_is_idempotent() {
        let source = r#"# user comment
[workspace]
members = ["game", "tools"]
resolver = "3"

[workspace.metadata.other]
keep = true
"#;
        let selected =
            plan_workspace_selection(source, "game-runtime").expect("workspace selection");
        assert!(selected.starts_with("# user comment\n"));
        assert!(selected.contains("members = [\"game\", \"tools\"]"));
        assert!(selected.contains("[workspace.metadata.other]"));
        assert!(selected.contains("keep = true"));
        assert!(selected.contains("[workspace.metadata.godot-rust]"));
        assert!(selected.contains("package = \"game-runtime\""));
        assert_eq!(
            plan_workspace_selection(&selected, "game-runtime").expect("idempotent"),
            selected
        );
    }

    #[test]
    fn workspace_selection_rejects_non_workspace_and_control_names() {
        assert!(
            plan_workspace_selection("[package]\nname = \"game\"\n", "game")
                .expect_err("package manifest")
                .contains("[workspace]")
        );
        assert!(
            plan_workspace_selection("[workspace]\n", "bad\nname")
                .expect_err("control name")
                .contains("control")
        );
    }

    #[test]
    fn setup_preserves_user_content_and_is_idempotent() {
        let project = TempProject::with_manifest(
            r#"# keep this project comment
[package]
name = "existing_game"
version = "0.1.0"

[dependencies]
godot_rs = { path = "../sdk" } # keep this dependency
serde = "1"
"#,
            Some("pub fn user_code() -> u32 { 7 }\n"),
        );
        let first = configure_project(&project.0).expect("first setup");
        assert_eq!(first.changed_files.len(), 7);
        let manifest = std::fs::read_to_string(project.0.join("Cargo.toml")).expect("manifest");
        assert!(manifest.contains("# keep this project comment"));
        assert!(manifest.contains("godot_rs = { path = \"../sdk\" } # keep this dependency"));
        assert!(manifest.contains("serde = \"1\""));
        assert!(manifest.contains("crate-type = [\"cdylib\", \"rlib\"]"));
        assert!(manifest.contains("[package.metadata.godot-rust]"));
        assert!(manifest.contains("godot = \"4.4\""));
        let crate_root = std::fs::read_to_string(project.0.join("src/lib.rs")).expect("crate root");
        assert!(crate_root.contains("pub fn user_code() -> u32 { 7 }"));
        assert!(crate_root.ends_with("\nmod scripts;\n"));
        let vscode_settings =
            std::fs::read_to_string(project.0.join(".vscode/settings.json")).expect("settings");
        assert!(vscode_settings.contains("rust-analyzer.linkedProjects"));
        assert!(project.0.join(".vscode/tasks.json").is_file());
        assert!(project.0.join(".vscode/launch.json").is_file());
        assert_eq!(
            std::fs::read_to_string(project.0.join(".cargo/config.toml")).expect("Cargo config"),
            "[build]\ntarget-dir = \".godot/rust/target\"\n\n\
             [env]\nGODOT_RS_GODOT = { value = \"4.4\", force = true }\n"
        );
        assert_eq!(
            std::fs::read_to_string(project.0.join("src/scripts/mod.rs")).expect("script index"),
            format!("{GENERATED_INDEX_HEADER_LINE}\ngodot_rs::script_module! {{\n}}\n")
        );

        let script_index = project.0.join("src/scripts/mod.rs");
        let windows_index = std::fs::read_to_string(&script_index)
            .expect("script index")
            .replace('\n', "\r\n");
        std::fs::write(&script_index, &windows_index).expect("CRLF script index");

        let second = configure_project(&project.0).expect("idempotent setup with CRLF index");
        assert!(second.changed_files.is_empty());
        assert_eq!(
            std::fs::read_to_string(script_index).expect("preserved script index"),
            windows_index
        );
    }

    #[test]
    fn setup_inherits_an_existing_workspace_dependency() {
        let project = TempProject::with_manifest(
            r#"[package]
name = "workspace_game"
version = "0.1.0"

[workspace]

[workspace.dependencies]
godot_rs = "0.1"
"#,
            Some(""),
        );
        configure_project(&project.0).expect("workspace-root package setup");
        let manifest = std::fs::read_to_string(project.0.join("Cargo.toml")).expect("manifest");
        assert!(manifest.contains("godot_rs = { workspace = true }"));
        assert_eq!(manifest.matches("godot_rs = \"0.1\"").count(), 1);
    }

    #[test]
    fn setup_preserves_an_explicit_script_api_target() {
        let project = TempProject::with_manifest(
            r#"[package]
name = "versioned_game"
version = "0.1.0"

[package.metadata.godot-rust]
mode = "script"
godot = "4.7"
"#,
            Some(""),
        );
        configure_project(&project.0).expect("versioned Script Mode setup");
        let manifest = std::fs::read_to_string(project.0.join("Cargo.toml")).expect("manifest");
        assert!(manifest.contains("godot = \"4.7\""));
        assert_eq!(manifest.matches("godot = ").count(), 1);
        assert!(
            std::fs::read_to_string(project.0.join(".cargo/config.toml"))
                .expect("Cargo config")
                .contains("GODOT_RS_GODOT = { value = \"4.7\", force = true }")
        );
    }

    #[test]
    fn cargo_api_config_tracks_metadata_changes_without_losing_user_settings() {
        let project = TempProject::with_manifest(
            "[package]\nname = \"game\"\nversion = \"0.1.0\"\n",
            Some(""),
        );
        std::fs::create_dir(project.0.join(".cargo")).expect("Cargo directory");
        std::fs::write(
            project.0.join(".cargo/config.toml"),
            "[build]\njobs = 2\n\n[env]\nUSER_SETTING = \"preserved\"\n",
        )
        .expect("Cargo config");

        let changed = sync_cargo_api_config(&project.0, GodotApiVersion::new(4, 7))
            .expect("sync Cargo API config");
        assert_eq!(changed, Some(project.0.join(".cargo/config.toml")));
        let config =
            std::fs::read_to_string(project.0.join(".cargo/config.toml")).expect("Cargo config");
        assert!(config.contains("jobs = 2"));
        assert!(config.contains("USER_SETTING = \"preserved\""));
        assert!(config.contains("GODOT_RS_GODOT = { value = \"4.7\", force = true }"));

        assert_eq!(
            sync_cargo_api_config(&project.0, GodotApiVersion::new(4, 7))
                .expect("idempotent Cargo API config sync"),
            None
        );
        sync_cargo_api_config(&project.0, GodotApiVersion::new(4, 5))
            .expect("changed Cargo API config sync");
        let config =
            std::fs::read_to_string(project.0.join(".cargo/config.toml")).expect("Cargo config");
        assert!(config.contains("GODOT_RS_GODOT = { value = \"4.5\", force = true }"));
        assert_eq!(config.matches("GODOT_RS_GODOT").count(), 1);
    }

    #[test]
    fn setup_rejects_conflicts_before_writing_any_file() {
        let manifest = r#"[package]
name = "native_game"
version = "0.1.0"

[package.metadata.godot-rust]
mode = "extension"
godot = "4.7"
"#;
        let project = TempProject::with_manifest(manifest, Some("pub fn untouched() {}\n"));
        let error = configure_project(&project.0).expect_err("Native conflict");
        assert!(error.contains("Extension Mode"));
        assert_eq!(
            std::fs::read_to_string(project.0.join("Cargo.toml")).expect("manifest"),
            manifest
        );
        assert_eq!(
            std::fs::read_to_string(project.0.join("src/lib.rs")).expect("crate root"),
            "pub fn untouched() {}\n"
        );
        assert!(!project.0.join(".cargo").exists());
        assert!(!project.0.join("src/scripts").exists());
    }

    #[test]
    fn setup_never_replaces_a_user_owned_script_index() {
        let project = TempProject::with_manifest(
            "[package]\nname = \"game\"\nversion = \"0.1.0\"\n",
            Some("mod scripts;\n"),
        );
        std::fs::create_dir(project.0.join("src/scripts")).expect("scripts directory");
        std::fs::write(
            project.0.join("src/scripts/mod.rs"),
            b"pub fn user_module() {}\n",
        )
        .expect("user index");
        let error = configure_project(&project.0).expect_err("user index conflict");
        assert!(error.contains("user-owned Rust module index"));
        let manifest = std::fs::read_to_string(project.0.join("Cargo.toml")).expect("manifest");
        assert!(!manifest.contains("godot_rs"));
        assert!(!project.0.join(".cargo").exists());
    }

    #[test]
    fn setup_does_not_repurpose_an_optional_or_renamed_dependency() {
        for dependency in [
            "godot_rs = { version = \"0.1\", optional = true }",
            "godot_rs = { package = \"another_sdk\", version = \"1\" }",
        ] {
            let manifest = format!(
                "[package]\nname = \"game\"\nversion = \"0.1.0\"\n\n[dependencies]\n{dependency}\n"
            );
            let project = TempProject::with_manifest(&manifest, Some(""));
            let error = configure_project(&project.0).expect_err("dependency conflict");
            assert!(
                error.contains("will not overwrite"),
                "unexpected setup error: {error}"
            );
            assert_eq!(
                std::fs::read_to_string(project.0.join("Cargo.toml")).expect("manifest"),
                manifest
            );
        }
    }

    #[test]
    fn failed_multi_file_write_restores_earlier_files() {
        let project = TempProject::with_manifest(
            "[package]\nname = \"game\"\nversion = \"0.1.0\"\n",
            Some(""),
        );
        let first_path = project.0.join("first.txt");
        std::fs::write(&first_path, b"original\n").expect("first file");
        let blocker = project.0.join("not-a-directory");
        std::fs::write(&blocker, b"blocker\n").expect("blocking file");
        let edits = vec![
            FileEdit {
                path: first_path.clone(),
                purpose: "first test file",
                original: Some(b"original\n".to_vec()),
                replacement: b"changed\n".to_vec(),
            },
            FileEdit {
                path: blocker.join("second.txt"),
                purpose: "second test file",
                original: None,
                replacement: b"new\n".to_vec(),
            },
        ];
        let error = apply_edits(&project.0, &edits).expect_err("second write must fail");
        assert!(error.contains("not a directory"));
        assert_eq!(
            std::fs::read(&first_path).expect("restored first file"),
            b"original\n"
        );
    }

    #[test]
    fn sdk_requirement_tracks_the_build_service_compatibility_line() {
        let version = env!("CARGO_PKG_VERSION");
        let expected = version
            .split_once('.')
            .and_then(|(major, rest)| {
                rest.split_once('.')
                    .map(|(minor, _)| format!("{major}.{minor}"))
            })
            .expect("workspace version has Major.Minor.Patch");
        assert_eq!(godot_rs_version_requirement(), expected);
    }
}
