use crate::managed_fs::{atomic_write, ensure_directory, has_managed_header};
use crate::{CargoPackageModel, CargoTargetModel, GodotRustMode};
use serde::Serialize;
use std::collections::HashSet;
use std::ffi::OsString;
use std::path::{Path, PathBuf};
use syn::parse::Parser;
use syn::punctuated::Punctuated;
use syn::{Attribute, Item, Meta, Token, Visibility};

const GENERATED_HEADER_LINE: &str =
    "// @generated by godot-rust; script files themselves are user-owned.";
const MAX_SCRIPT_BYTES: u64 = 4 * 1024 * 1024;
const MAX_SCRIPT_COUNT: usize = 10_000;
const MAX_UID_BYTES: u64 = 64;

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct ScriptIndexEntry {
    pub source_path: PathBuf,
    pub resource_path: String,
    pub rust_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resource_uid: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct ScriptIndexReport {
    pub scripts_path: PathBuf,
    pub index_path: PathBuf,
    pub module_name: String,
    pub changed: bool,
    pub scripts: Vec<ScriptIndexEntry>,
}

pub fn sync_configured_script_index(
    project_root: impl AsRef<Path>,
    package: &CargoPackageModel,
) -> Result<Option<ScriptIndexReport>, String> {
    if package.godot_rust_mode != Some(GodotRustMode::Script) {
        return Ok(None);
    }
    if package.scripts_path.is_none() {
        return Ok(None);
    }
    sync_script_index(project_root, package).map(Some)
}

pub fn sync_script_index(
    project_root: impl AsRef<Path>,
    package: &CargoPackageModel,
) -> Result<ScriptIndexReport, String> {
    if package.godot_rust_mode != Some(GodotRustMode::Script) {
        return Err(format!(
            "Cargo package `{}` is not configured for Script Mode",
            package.name
        ));
    }
    let scripts_path = package.scripts_path.as_ref().ok_or_else(|| {
        format!(
            "Cargo package `{}` has no configured Rust script directory",
            package.name
        )
    })?;
    let [target] = package.cdylib_targets.as_slice() else {
        return Err(format!(
            "Script Mode package `{}` must have exactly one cdylib target",
            package.name
        ));
    };
    let project_root = project_root.as_ref().canonicalize().map_err(|error| {
        format!(
            "could not resolve Godot project root `{}`: {error}",
            project_root.as_ref().display()
        )
    })?;
    validate_module_layout(scripts_path, target)?;
    ensure_directory(scripts_path, "Rust script directory")?;
    let scripts_path = scripts_path.canonicalize().map_err(|error| {
        format!(
            "could not resolve Rust script directory `{}`: {error}",
            scripts_path.display()
        )
    })?;
    if !scripts_path.starts_with(&project_root) {
        return Err(format!(
            "Rust script directory must remain inside the Godot project: {}",
            scripts_path.display()
        ));
    }

    let mut source_paths = Vec::new();
    collect_script_paths(&scripts_path, &mut source_paths)?;
    source_paths.sort();
    if source_paths.len() > MAX_SCRIPT_COUNT {
        return Err(format!(
            "Rust script directory contains {} scripts; the safety limit is {MAX_SCRIPT_COUNT}",
            source_paths.len()
        ));
    }

    let mut aliases = HashSet::new();
    let mut entries = Vec::with_capacity(source_paths.len());
    let mut generated_modules = Vec::with_capacity(source_paths.len());
    for source_path in source_paths {
        let entry = inspect_script(&project_root, &source_path)?;
        let relative = source_path
            .strip_prefix(&scripts_path)
            .expect("collected script is inside the configured directory");
        let relative_text = resource_relative_path(relative)?;
        let alias = format!("godot_rs_script_{:016x}", stable_hash(&entry.resource_path));
        if !aliases.insert(alias.clone()) {
            return Err(format!(
                "generated Rust module identity collided for `{}`",
                entry.resource_path
            ));
        }
        generated_modules.push((alias, relative_text, entry.rust_type.clone()));
        entries.push(entry);
    }

    let index_path = scripts_path.join("mod.rs");
    let contents = render_index(&entries, &generated_modules);
    let existing = match std::fs::read_to_string(&index_path) {
        Ok(existing) => {
            if !has_managed_header(existing.as_bytes(), GENERATED_HEADER_LINE.as_bytes()) {
                return Err(format!(
                    "refusing to replace user-owned Rust module index `{}`; move it or add the godot-rust generated header",
                    index_path.display()
                ));
            }
            Some(existing)
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => {
            return Err(format!(
                "could not read Rust module index `{}`: {error}",
                index_path.display()
            ));
        }
    };
    let changed = existing.as_deref() != Some(contents.as_str());
    if changed {
        atomic_write(
            &index_path,
            contents.as_bytes(),
            "generated Rust script module index",
        )?;
    }
    let module_name = module_name(target, &scripts_path)?;
    Ok(ScriptIndexReport {
        scripts_path,
        index_path,
        module_name,
        changed,
        scripts: entries,
    })
}

fn validate_module_layout(scripts_path: &Path, target: &CargoTargetModel) -> Result<(), String> {
    let target_parent = target.src_path.parent().ok_or_else(|| {
        format!(
            "Cargo cdylib source has no parent directory: {}",
            target.src_path.display()
        )
    })?;
    if scripts_path.parent() != Some(target_parent) {
        return Err(format!(
            "Rust script directory `{}` must be next to the selected crate root `{}`",
            scripts_path.display(),
            target.src_path.display()
        ));
    }
    let module_name = module_name(target, scripts_path)?;
    let metadata = std::fs::metadata(&target.src_path).map_err(|error| {
        format!(
            "could not inspect selected crate root `{}`: {error}",
            target.src_path.display()
        )
    })?;
    if metadata.len() > MAX_SCRIPT_BYTES {
        return Err(format!(
            "selected crate root exceeds the {MAX_SCRIPT_BYTES} byte safety limit: {}",
            target.src_path.display()
        ));
    }
    let source = std::fs::read_to_string(&target.src_path).map_err(|error| {
        format!(
            "could not read selected crate root `{}` as UTF-8: {error}",
            target.src_path.display()
        )
    })?;
    let syntax = syn::parse_file(&source).map_err(|error| {
        format!(
            "selected crate root `{}` is not valid Rust: {error}",
            target.src_path.display()
        )
    })?;
    let declared = syntax.items.iter().any(
        |item| matches!(item, Item::Mod(module) if module.ident == module_name && module.content.is_none()),
    );
    if !declared {
        return Err(format!(
            "selected crate root `{}` must declare `mod {module_name};` so Cargo compiles Godot Rust scripts",
            target.src_path.display()
        ));
    }
    Ok(())
}

fn module_name(target: &CargoTargetModel, scripts_path: &Path) -> Result<String, String> {
    let name = scripts_path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            format!(
                "Rust script directory name is not UTF-8: {}",
                scripts_path.display()
            )
        })?;
    syn::parse_str::<syn::Ident>(name).map_err(|_| {
        format!(
            "Rust script directory `{}` must end in a valid Rust module name next to `{}`",
            scripts_path.display(),
            target.src_path.display()
        )
    })?;
    Ok(name.to_owned())
}

fn collect_script_paths(directory: &Path, output: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = std::fs::read_dir(directory).map_err(|error| {
        format!(
            "could not scan Rust script directory `{}`: {error}",
            directory.display()
        )
    })?;
    for entry in entries {
        let entry = entry.map_err(|error| {
            format!(
                "could not read an entry in Rust script directory `{}`: {error}",
                directory.display()
            )
        })?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(|error| {
            format!(
                "could not inspect Rust script path `{}`: {error}",
                path.display()
            )
        })?;
        if file_type.is_symlink() {
            return Err(format!(
                "Rust script discovery does not follow symbolic links: {}",
                path.display()
            ));
        }
        if file_type.is_dir() {
            collect_script_paths(&path, output)?;
        } else if file_type.is_file()
            && path.extension().is_some_and(|extension| extension == "rs")
            && path.file_name().is_some_and(|name| name != "mod.rs")
        {
            output.push(path);
        }
    }
    Ok(())
}

fn inspect_script(project_root: &Path, source_path: &Path) -> Result<ScriptIndexEntry, String> {
    let metadata = std::fs::metadata(source_path).map_err(|error| {
        format!(
            "could not inspect Rust script `{}`: {error}",
            source_path.display()
        )
    })?;
    if metadata.len() > MAX_SCRIPT_BYTES {
        return Err(format!(
            "Rust script exceeds the {MAX_SCRIPT_BYTES} byte safety limit: {}",
            source_path.display()
        ));
    }
    let source = std::fs::read_to_string(source_path).map_err(|error| {
        format!(
            "could not read Rust script `{}` as UTF-8: {error}",
            source_path.display()
        )
    })?;
    let syntax = syn::parse_file(&source).map_err(|error| {
        format!(
            "Rust script `{}` cannot be parsed: {error}",
            source_path.display()
        )
    })?;
    let candidates = syntax
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Struct(item) if has_attachable_script_attribute(&item.attrs) => Some(item),
            _ => None,
        })
        .collect::<Vec<_>>();
    let [script] = candidates.as_slice() else {
        return Err(format!(
            "Rust script `{}` must contain exactly one `#[script(base = GodotClass)]` struct; found {}",
            source_path.display(),
            candidates.len()
        ));
    };
    if !matches!(script.vis, Visibility::Public(_)) {
        return Err(format!(
            "Rust script type `{}` in `{}` must be `pub` so the generated module index can register it",
            script.ident,
            source_path.display()
        ));
    }
    let relative = source_path.strip_prefix(project_root).map_err(|_| {
        format!(
            "Rust script is outside the Godot project: {}",
            source_path.display()
        )
    })?;
    let resource_path = format!("res://{}", resource_relative_path(relative)?);
    let resource_uid = read_uid(source_path)?;
    Ok(ScriptIndexEntry {
        source_path: source_path.to_owned(),
        resource_path,
        rust_type: script.ident.to_string(),
        resource_uid,
    })
}

fn has_attachable_script_attribute(attributes: &[Attribute]) -> bool {
    attributes.iter().any(|attribute| {
        let is_script = attribute
            .path()
            .segments
            .last()
            .is_some_and(|segment| segment.ident == "script");
        if !is_script {
            return false;
        }
        let Meta::List(list) = &attribute.meta else {
            return false;
        };
        Punctuated::<Meta, Token![,]>::parse_terminated
            .parse2(list.tokens.clone())
            .ok()
            .is_some_and(|arguments| {
                arguments.iter().any(
                    |argument| matches!(argument, Meta::NameValue(value) if value.path.is_ident("base")),
                )
            })
    })
}

fn read_uid(source_path: &Path) -> Result<Option<String>, String> {
    let mut uid_file = OsString::from(source_path.as_os_str());
    uid_file.push(".uid");
    let uid_file = PathBuf::from(uid_file);
    let metadata = match std::fs::symlink_metadata(&uid_file) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(format!(
                "could not inspect Resource UID file `{}`: {error}",
                uid_file.display()
            ));
        }
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(format!(
            "Resource UID file must be a regular file: {}",
            uid_file.display()
        ));
    }
    if metadata.len() > MAX_UID_BYTES {
        return Err(format!(
            "Resource UID file exceeds the {MAX_UID_BYTES} byte safety limit: {}",
            uid_file.display()
        ));
    }
    let contents = std::fs::read_to_string(&uid_file).map_err(|error| {
        format!(
            "could not read Resource UID file `{}` as UTF-8: {error}",
            uid_file.display()
        )
    })?;
    let text = contents.lines().next().unwrap_or_default();
    parse_resource_uid_text(text).ok_or_else(|| {
        format!(
            "Resource UID file has invalid canonical text: {}",
            uid_file.display()
        )
    })?;
    Ok(Some(text.to_owned()))
}

fn parse_resource_uid_text(text: &str) -> Option<i64> {
    let digits = text.as_bytes().strip_prefix(b"uid://")?;
    if digits.is_empty() || (digits.len() > 1 && digits[0] == b'a') {
        return None;
    }
    let mut uid = 0_u64;
    for digit in digits {
        let value = match *digit {
            b'a'..=b'y' => u64::from(*digit - b'a'),
            b'0'..=b'8' => u64::from(*digit - b'0') + 25,
            _ => return None,
        };
        uid = uid.checked_mul(34)?.checked_add(value)?;
    }
    (uid <= i64::MAX as u64).then_some(uid as i64)
}

fn resource_relative_path(path: &Path) -> Result<String, String> {
    path.components()
        .map(|component| {
            component
                .as_os_str()
                .to_str()
                .map(str::to_owned)
                .ok_or_else(|| format!("Godot resource path is not UTF-8: {}", path.display()))
        })
        .collect::<Result<Vec<_>, _>>()
        .map(|components| components.join("/"))
}

fn render_index(entries: &[ScriptIndexEntry], modules: &[(String, String, String)]) -> String {
    let mut output = format!("{GENERATED_HEADER_LINE}\n");
    for (alias, path, _) in modules {
        output.push_str(&format!("#[path = {path:?}]\nmod {alias};\n"));
    }
    if !modules.is_empty() {
        output.push('\n');
    }
    output.push_str("godot_rs::script_module! {\n");
    for (entry, (alias, _, type_name)) in entries.iter().zip(modules) {
        let uid = entry.resource_uid.as_deref().unwrap_or("");
        output.push_str(&format!(
            "    {alias}::{type_name} => ({:?}, {:?}),\n",
            entry.resource_path, uid
        ));
    }
    output.push_str("}\n");
    output
}

fn stable_hash(value: &str) -> u64 {
    value
        .as_bytes()
        .iter()
        .fold(14_695_981_039_346_656_037, |hash, byte| {
            (hash ^ u64::from(*byte)).wrapping_mul(1_099_511_628_211)
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_TEST: AtomicU64 = AtomicU64::new(0);

    struct TempProject(PathBuf);

    impl TempProject {
        fn new() -> Self {
            let id = NEXT_TEST.fetch_add(1, Ordering::Relaxed);
            let root = std::env::temp_dir().join(format!(
                "godot-rust-script-index-{}-{id}",
                std::process::id()
            ));
            std::fs::create_dir_all(root.join("src/scripts/actors")).expect("script directory");
            std::fs::write(root.join("project.godot"), b"[application]\n").expect("Godot project");
            std::fs::write(root.join("Cargo.toml"), b"[package]\nname = \"game\"\n")
                .expect("manifest");
            std::fs::write(root.join("src/lib.rs"), b"mod scripts;\n").expect("crate root");
            Self(root)
        }

        fn package(&self) -> CargoPackageModel {
            CargoPackageModel {
                id: "game 0.1.0".to_owned(),
                name: "game".to_owned(),
                manifest_path: self.0.join("Cargo.toml"),
                workspace_default: true,
                godot_rs_dependency: true,
                godot_rust_enabled: true,
                godot_rust_mode: Some(GodotRustMode::Script),
                godot_api: None,
                scripts_path: Some(self.0.join("src/scripts")),
                editor: crate::EditorWorkflowConfig::default(),
                script_mode_configured: true,
                configuration_issues: Vec::new(),
                cdylib_targets: vec![CargoTargetModel {
                    name: "game".to_owned(),
                    src_path: self.0.join("src/lib.rs"),
                }],
            }
        }
    }

    impl Drop for TempProject {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn scripts_are_parsed_sorted_and_written_as_a_stable_index() {
        let project = TempProject::new();
        std::fs::write(
            project.0.join("src/scripts/zeta.rs"),
            b"use godot_rs::prelude::*;\n#[script(base = Node)]\npub struct Zeta;\n",
        )
        .expect("zeta");
        std::fs::write(
            project.0.join("src/scripts/actors/player.rs"),
            b"#[godot_rs::script(base = Node2D)]\npub struct Player;\n",
        )
        .expect("player");
        std::fs::write(
            project.0.join("src/scripts/actors/player.rs.uid"),
            b"uid://b2\n",
        )
        .expect("UID");

        let first = sync_script_index(&project.0, &project.package()).expect("first sync");
        assert!(first.changed);
        assert_eq!(first.scripts.len(), 2);
        assert_eq!(
            first
                .scripts
                .iter()
                .map(|script| script.resource_path.as_str())
                .collect::<Vec<_>>(),
            [
                "res://src/scripts/actors/player.rs",
                "res://src/scripts/zeta.rs",
            ]
        );
        assert_eq!(first.scripts[0].resource_uid.as_deref(), Some("uid://b2"));
        let index = std::fs::read_to_string(&first.index_path).expect("index");
        assert!(index.starts_with(GENERATED_HEADER_LINE));
        assert!(index.contains("#[path = \"actors/player.rs\"]"));
        assert!(
            index.contains("::Player => (\"res://src/scripts/actors/player.rs\", \"uid://b2\")")
        );
        assert!(index.contains("::Zeta => (\"res://src/scripts/zeta.rs\", \"\")"));

        let windows_index = index.replace('\n', "\r\n");
        std::fs::write(&first.index_path, windows_index).expect("CRLF index");
        let second =
            sync_script_index(&project.0, &project.package()).expect("sync existing CRLF index");
        assert!(second.changed);
        assert_eq!(
            std::fs::read_to_string(&second.index_path).expect("normalized index"),
            index
        );

        let third = sync_script_index(&project.0, &project.package()).expect("third sync");
        assert!(!third.changed);
    }

    #[test]
    fn user_owned_index_and_private_script_types_are_rejected() {
        let project = TempProject::new();
        std::fs::write(
            project.0.join("src/scripts/private.rs"),
            b"#[script(base = Node)]\nstruct Private;\n",
        )
        .expect("private script");
        let error =
            sync_script_index(&project.0, &project.package()).expect_err("private type rejected");
        assert!(error.contains("must be `pub`"));

        std::fs::write(
            project.0.join("src/scripts/private.rs"),
            b"#[script(base = Node)]\npub struct Public;\n",
        )
        .expect("public script");
        std::fs::write(project.0.join("src/scripts/mod.rs"), b"mod user_owned;\n")
            .expect("user index");
        let error =
            sync_script_index(&project.0, &project.package()).expect_err("user index rejected");
        assert!(error.contains("refusing to replace user-owned"));
    }

    #[test]
    fn resource_uid_text_must_be_canonical() {
        assert_eq!(parse_resource_uid_text("uid://c2"), Some(95));
        assert!(parse_resource_uid_text("uid://aa").is_none());
        assert!(parse_resource_uid_text("uid://z").is_none());
        assert!(parse_resource_uid_text("uid://9").is_none());
    }
}
