[package]
name = "godot_rs_host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
godot_rs_api.workspace = true
libloading.workspace = true
proc-macro2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
syn.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[lints]
workspace = true
