use std::fmt::Write;

use crate::ExtensionApi;

/// Emits a deterministic Rust index of an official Godot API.
#[must_use]
pub fn generate_api_snapshot(api: &ExtensionApi, source_sha256: &str) -> String {
    let inventory = api.inventory();
    let mut classes: Vec<_> = api.classes.iter().collect();
    classes.sort_by(|left, right| left.name.cmp(&right.name));
    let mut methods: Vec<_> = api
        .classes
        .iter()
        .flat_map(|class| {
            class
                .methods
                .iter()
                .map(move |method| (class.name.as_str(), method))
        })
        .collect();
    methods.sort_by(|left, right| {
        (left.0, left.1.name.as_str()).cmp(&(right.0, right.1.name.as_str()))
    });
    let mut builtin_sizes: Vec<_> = api
        .builtin_class_sizes
        .iter()
        .flat_map(|configuration| {
            configuration
                .sizes
                .iter()
                .map(move |size| (configuration.build_configuration.as_str(), size))
        })
        .collect();
    builtin_sizes.sort_by(|left, right| {
        (left.0, left.1.name.as_str()).cmp(&(right.0, right.1.name.as_str()))
    });

    let mut output = String::new();
    writeln!(output, "// @generated by godot_rs_codegen; DO NOT EDIT.").unwrap();
    writeln!(
        output,
        "// Godot Engine copyright and MIT notice: GODOT_LICENSE.md in the packaged addon."
    )
    .unwrap();
    writeln!(
        output,
        "// Source: Godot {}.{}.{} {} {}",
        api.header.version_major,
        api.header.version_minor,
        api.header.version_patch,
        api.header.version_status,
        api.header.version_build
    )
    .unwrap();
    writeln!(output).unwrap();
    writeln!(
        output,
        "pub const GODOT_API_VERSION: (u32, u32, u32) = ({}, {}, {});",
        api.header.version_major, api.header.version_minor, api.header.version_patch
    )
    .unwrap();
    writeln!(
        output,
        "pub const GODOT_API_SHA256: &str =\n    {source_sha256:?};"
    )
    .unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[doc(hidden)]").unwrap();
    writeln!(output, "#[macro_export]").unwrap();
    writeln!(output, "macro_rules! godot_rs_for_each_engine_class {{").unwrap();
    writeln!(output, "    ($callback:ident) => {{").unwrap();
    writeln!(output, "        $callback!(").unwrap();
    for class in &classes {
        writeln!(output, "            {},", class.name).unwrap();
    }
    writeln!(output, "        );").unwrap();
    writeln!(output, "    }};").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    writeln!(
        output,
        "pub const ENGINE_CLASS_COUNT: usize = {};",
        api.classes.len()
    )
    .unwrap();
    writeln!(
        output,
        "pub const BUILTIN_CLASS_COUNT: usize = {};",
        api.builtin_classes.len()
    )
    .unwrap();
    writeln!(
        output,
        "pub const UTILITY_FUNCTION_COUNT: usize = {};",
        api.utility_functions.len()
    )
    .unwrap();
    writeln!(
        output,
        "pub const ENGINE_METHOD_COUNT: usize = {};",
        methods.len()
    )
    .unwrap();
    for (name, count) in [
        ("ENGINE_PROPERTY_COUNT", inventory.engine_property_count),
        ("ENGINE_SIGNAL_COUNT", inventory.engine_signal_count),
        ("ENGINE_ENUM_COUNT", inventory.engine_enum_count),
        ("ENGINE_CONSTANT_COUNT", inventory.engine_constant_count),
        (
            "BUILTIN_CONSTRUCTOR_COUNT",
            inventory.builtin_constructor_count,
        ),
        ("BUILTIN_OPERATOR_COUNT", inventory.builtin_operator_count),
        ("BUILTIN_METHOD_COUNT", inventory.builtin_method_count),
        ("BUILTIN_MEMBER_COUNT", inventory.builtin_member_count),
        ("BUILTIN_CONSTANT_COUNT", inventory.builtin_constant_count),
        ("BUILTIN_ENUM_COUNT", inventory.builtin_enum_count),
        ("GLOBAL_CONSTANT_COUNT", inventory.global_constant_count),
        ("GLOBAL_ENUM_COUNT", inventory.global_enum_count),
        ("SINGLETON_COUNT", inventory.singleton_count),
        ("NATIVE_STRUCTURE_COUNT", inventory.native_structure_count),
    ] {
        writeln!(output, "pub const {name}: usize = {count};").unwrap();
    }
    writeln!(output).unwrap();
    writeln!(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(output, "pub struct EngineClassSummary {{").unwrap();
    writeln!(output, "    pub name: &'static str,").unwrap();
    writeln!(output, "    pub inherits: Option<&'static str>,").unwrap();
    writeln!(output, "    pub method_count: u32,").unwrap();
    writeln!(output, "    pub property_count: u32,").unwrap();
    writeln!(output, "    pub signal_count: u32,").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[rustfmt::skip]").unwrap();
    writeln!(
        output,
        "pub static ENGINE_CLASSES: &[EngineClassSummary] = &["
    )
    .unwrap();
    for class in &classes {
        let inherits = class
            .inherits
            .as_ref()
            .map_or_else(|| "None".to_owned(), |parent| format!("Some({parent:?})"));
        writeln!(
            output,
            "    EngineClassSummary {{ name: {:?}, inherits: {}, method_count: {}, property_count: {}, signal_count: {} }},",
            class.name,
            inherits,
            class.methods.len(),
            class.properties.len(),
            class.signals.len()
        )
        .unwrap();
    }
    writeln!(output, "];").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(output, "pub enum MethodCallKind {{").unwrap();
    writeln!(output, "    Ptrcall,").unwrap();
    writeln!(output, "    VariantCall,").unwrap();
    writeln!(output, "    Virtual,").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(output, "pub struct EngineMethodSummary {{").unwrap();
    writeln!(output, "    pub class: &'static str,").unwrap();
    writeln!(output, "    pub name: &'static str,").unwrap();
    writeln!(output, "    pub hash: Option<u64>,").unwrap();
    writeln!(output, "    pub call_kind: MethodCallKind,").unwrap();
    writeln!(output, "    pub argument_count: u32,").unwrap();
    writeln!(output, "    pub is_const: bool,").unwrap();
    writeln!(output, "    pub is_static: bool,").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[rustfmt::skip]").unwrap();
    writeln!(
        output,
        "pub static ENGINE_METHODS: &[EngineMethodSummary] = &["
    )
    .unwrap();
    for (class, method) in methods {
        let call_kind = if method.is_virtual {
            "MethodCallKind::Virtual"
        } else if method.is_vararg {
            "MethodCallKind::VariantCall"
        } else {
            "MethodCallKind::Ptrcall"
        };
        writeln!(
            output,
            "    EngineMethodSummary {{ class: {class:?}, name: {:?}, hash: {:?}, call_kind: {call_kind}, argument_count: {}, is_const: {}, is_static: {} }},",
            method.name,
            method.hash,
            method.arguments.len(),
            method.is_const,
            method.is_static
        )
        .unwrap();
    }
    writeln!(output, "];").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(output, "pub struct BuiltinSizeSummary {{").unwrap();
    writeln!(output, "    pub configuration: &'static str,").unwrap();
    writeln!(output, "    pub name: &'static str,").unwrap();
    writeln!(output, "    pub size: u64,").unwrap();
    writeln!(output, "}}").unwrap();
    writeln!(output).unwrap();
    writeln!(output, "#[rustfmt::skip]").unwrap();
    writeln!(
        output,
        "pub static BUILTIN_SIZES: &[BuiltinSizeSummary] = &["
    )
    .unwrap();
    for (configuration, size) in builtin_sizes {
        writeln!(
            output,
            "    BuiltinSizeSummary {{ configuration: {configuration:?}, name: {:?}, size: {} }},",
            size.name, size.size
        )
        .unwrap();
    }
    writeln!(output, "];").unwrap();
    output
}
