use sha2::{Digest, Sha256};
use std::error::Error;
use std::fs;
use std::path::Path;

/// Generates Raw Rust FFI from Godot's exact official C header.
pub fn generate_raw_ffi(header_path: &Path) -> Result<String, Box<dyn Error>> {
    let header = fs::read(header_path)?;
    let header_sha256 = format!("{:x}", Sha256::digest(&header));
    let header_path = header_path
        .to_str()
        .ok_or("GDExtension header path is not valid UTF-8")?;

    let bindings = bindgen::Builder::default()
        .header(header_path)
        .clang_arg("-x")
        .clang_arg("c")
        .allowlist_item("GDExtension.*")
        .allowlist_item("GDObjectInstanceID")
        // Godot may add enum values in a later compatible engine release.
        // A Rust enum makes receiving an unknown C value undefined behavior,
        // so keep every C enum as an integer-backed transparent newtype.
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        // Bindgen otherwise freezes the generator host's wchar_t width into
        // the checked-in output. Godot's wide-string ABI uses 16 bits on
        // Windows and 32 bits on the other supported desktop platforms.
        .blocklist_type("wchar_t")
        .use_core()
        .derive_copy(true)
        .derive_debug(true)
        .derive_default(false)
        .generate_comments(true)
        .layout_tests(false)
        .generate()?;

    Ok(format!(
        "// @generated by godot_rs_codegen from Godot's official header; DO NOT EDIT.\n\
         // Godot Engine copyright and MIT notice: GODOT_LICENSE.md in the packaged addon.\n\
         pub const GODOT_GDEXTENSION_INTERFACE_SHA256: &str =\n    {header_sha256:?};\n\n\
         #[cfg(target_os = \"windows\")]\n\
         pub type wchar_t = u16;\n\
         #[cfg(not(target_os = \"windows\"))]\n\
         pub type wchar_t = ::core::ffi::c_int;\n\n\
         {bindings}"
    ))
}
